version: '3.8'

services:
  build-server:
    image: ghcr.io/junwu-git/build-server:latest
    container_name: build-server
    restart: on-failure:5
    ports:
      - "8889:8889"
    env_file:
      - .env
    deploy:
      resources:
        limits:
          memory: 1024M          
    volumes:
      - ./auth:/home/user/auth
      - ./debug-screenshots:/home/user/debug-screenshots