# docker-compose.yml

version: '3.8'

services:
  build-server:
    image: ghcr.io/junwu-git/build-server:latest
    container_name: build-server
    restart: on-failure:5
    
    environment:
      - TARGET_UID=${UID}
      - TARGET_GID=${GID}
      - API_KEYS=${API_KEYS} 
      - STREAMING_MODE=fake
      - FAILURE_THRESHOLD=0
      - MAX_RETRIES=3
      - RETRY_DELAY=3000
      - IMMEDIATE_SWITCH_STATUS_CODES=429,503
      - TZ=Asia/Shanghai
    ports:
      - "8889:8889"
    volumes:
      # 确保容器内的路径是 /app/...
      - ./auth:/app/auth
      - ./debug-screenshots:/app/debug-screenshots
      
